import type { Agent } from './types'

export const DEMO_AGENTS: Agent[] = [
  {
    id: 'demo-ceo',
    name: 'CEO',
    title: 'Chief Executive Officer',
    role: 'ceo',
    icon: 'crown',
    status: 'running',
    activeRun: {
      id: 'run-ceo-1',
      status: 'running',
      startedAt: new Date(Date.now() - 120000).toISOString(),
    },
    urlKey: 'ceo',
  },
  {
    id: 'demo-cto',
    name: 'CTO',
    title: 'Chief Technology Officer',
    role: 'cto',
    icon: 'chip',
    status: 'running',
    activeRun: null,
    urlKey: 'cto',
  },
  {
    id: 'demo-lead-app',
    name: 'Lead App Engineer',
    title: 'Lead Application Engineer',
    role: 'engineer',
    icon: 'rocket',
    status: 'running',
    activeRun: {
      id: 'run-lae-1',
      status: 'running',
      startedAt: new Date(Date.now() - 45000).toISOString(),
    },
    urlKey: 'lead-app-engineer',
  },
  {
    id: 'demo-designer',
    name: 'Product Designer',
    title: 'Product Designer',
    role: 'designer',
    icon: 'palette',
    status: 'running',
    activeRun: null,
    urlKey: 'product-designer',
  },
  {
    id: 'demo-web-1',
    name: 'Senior Web Engineer',
    title: 'Senior Web Engineer',
    role: 'engineer',
    icon: 'code',
    status: 'running',
    activeRun: {
      id: 'run-web1-1',
      status: 'running',
      startedAt: new Date(Date.now() - 200000).toISOString(),
    },
    urlKey: 'senior-web-engineer',
  },
  {
    id: 'demo-web-2',
    name: 'Senior Web Engineer II',
    title: 'Senior Web Engineer II',
    role: 'engineer',
    icon: 'code',
    status: 'running',
    activeRun: null,
    urlKey: 'senior-web-engineer-ii',
  },
  {
    id: 'demo-mobile-ios',
    name: 'Mobile Engineer iOS',
    title: 'Senior Mobile Engineer iOS',
    role: 'engineer',
    icon: 'mobile',
    status: 'running',
    activeRun: null,
    urlKey: 'mobile-engineer-ios',
  },
  {
    id: 'demo-mobile-android',
    name: 'Mobile Engineer Android',
    title: 'Senior Mobile Engineer Android',
    role: 'engineer',
    icon: 'mobile',
    status: 'running',
    activeRun: null,
    urlKey: 'mobile-engineer-android',
  },
]
