import type { Agent, Issue, ActivityEvent } from './types'

export const DEMO_AGENTS: Agent[] = [
  {
    id: 'demo-ceo',
    name: 'CEO',
    title: 'Chief Executive Officer',
    role: 'ceo',
    icon: 'crown',
    status: 'running',
    activeRun: {
      id: 'run-ceo-1',
      status: 'running',
      startedAt: new Date(Date.now() - 120000).toISOString(),
    },
    urlKey: 'ceo',
    currentIssue: { identifier: 'APPU-101', title: 'Q2 product strategy review' },
  },
  {
    id: 'demo-cto',
    name: 'CTO',
    title: 'Chief Technology Officer',
    role: 'cto',
    icon: 'chip',
    status: 'running',
    activeRun: null,
    urlKey: 'cto',
  },
  {
    id: 'demo-lead-app',
    name: 'Lead App Engineer',
    title: 'Lead Application Engineer',
    role: 'engineer',
    icon: 'rocket',
    status: 'running',
    activeRun: {
      id: 'run-lae-1',
      status: 'running',
      startedAt: new Date(Date.now() - 45000).toISOString(),
    },
    urlKey: 'lead-app-engineer',
    currentIssue: { identifier: 'APPU-149', title: 'Mission Control Phase 2 enhancements' },
  },
  {
    id: 'demo-designer',
    name: 'Product Designer',
    title: 'Product Designer',
    role: 'designer',
    icon: 'palette',
    status: 'running',
    activeRun: null,
    urlKey: 'product-designer',
  },
  {
    id: 'demo-web-1',
    name: 'Senior Web Engineer',
    title: 'Senior Web Engineer',
    role: 'engineer',
    icon: 'code',
    status: 'running',
    activeRun: {
      id: 'run-web1-1',
      status: 'running',
      startedAt: new Date(Date.now() - 200000).toISOString(),
    },
    urlKey: 'senior-web-engineer',
    currentIssue: { identifier: 'APPU-148', title: 'Mission Control Phase 1 — CSS tokens' },
  },
  {
    id: 'demo-web-2',
    name: 'Senior Web Engineer II',
    title: 'Senior Web Engineer II',
    role: 'engineer',
    icon: 'code',
    status: 'running',
    activeRun: {
      id: 'run-web2-1',
      status: 'running',
      startedAt: new Date(Date.now() - 5000).toISOString(),
    },
    urlKey: 'senior-web-engineer-ii',
    currentIssue: { identifier: 'APPU-149', title: 'Mission Control Phase 2 enhancements' },
  },
  {
    id: 'demo-mobile-ios',
    name: 'Mobile Engineer iOS',
    title: 'Senior Mobile Engineer iOS',
    role: 'engineer',
    icon: 'mobile',
    status: 'running',
    activeRun: null,
    urlKey: 'mobile-engineer-ios',
  },
  {
    id: 'demo-mobile-android',
    name: 'Mobile Engineer Android',
    title: 'Senior Mobile Engineer Android',
    role: 'engineer',
    icon: 'mobile',
    status: 'running',
    activeRun: null,
    urlKey: 'mobile-engineer-android',
  },
]

export const DEMO_PIPELINE_ISSUES: Issue[] = [
  {
    id: 'demo-ip-1',
    identifier: 'APPU-148',
    title: 'Mission Control Phase 1 — CSS tokens, typography, animations & badges',
    status: 'in_progress',
    priority: 'high',
    assigneeAgentId: 'demo-web-1',
    updatedAt: new Date(Date.now() - 200000).toISOString(),
    startedAt: new Date(Date.now() - 200000).toISOString(),
  },
  {
    id: 'demo-ip-2',
    identifier: 'APPU-149',
    title: 'Mission Control Phase 2 — Glassmorphism, pipeline tabs, activity feed',
    status: 'in_progress',
    priority: 'high',
    assigneeAgentId: 'demo-web-2',
    updatedAt: new Date(Date.now() - 5000).toISOString(),
    startedAt: new Date(Date.now() - 5000).toISOString(),
  },
  {
    id: 'demo-ip-3',
    identifier: 'APPU-101',
    title: 'Q2 product strategy review and roadmap planning',
    status: 'in_progress',
    priority: 'critical',
    assigneeAgentId: 'demo-ceo',
    updatedAt: new Date(Date.now() - 120000).toISOString(),
    startedAt: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'demo-ip-4',
    identifier: 'APPU-145',
    title: 'Design UX/UI enhancement plan for Mission Control dashboard',
    status: 'in_progress',
    priority: 'medium',
    assigneeAgentId: 'demo-designer',
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    startedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-blocked-1',
    identifier: 'APPU-150',
    title: 'Mission Control Phase 3A — Agent detail drawer & command palette',
    status: 'blocked',
    priority: 'medium',
    assigneeAgentId: 'demo-web-1',
    blockedBy: [
      { id: 'demo-ip-1', identifier: 'APPU-148', title: 'Phase 1 CSS tokens', status: 'in_progress' },
      { id: 'demo-ip-2', identifier: 'APPU-149', title: 'Phase 2 enhancements', status: 'in_progress' },
    ],
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'demo-blocked-2',
    identifier: 'APPU-151',
    title: 'Mission Control Phase 3B — KPI sparklines & activity heatmap',
    status: 'blocked',
    priority: 'low',
    assigneeAgentId: 'demo-web-2',
    blockedBy: [
      { id: 'demo-ip-2', identifier: 'APPU-149', title: 'Phase 2 enhancements', status: 'in_progress' },
    ],
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'demo-ir-1',
    identifier: 'APPU-138',
    title: 'Implement push notification system for mobile',
    status: 'in_review',
    priority: 'high',
    assigneeAgentId: 'demo-mobile-ios',
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    startedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'demo-ir-2',
    identifier: 'APPU-133',
    title: 'Add dark mode support to settings screen',
    status: 'in_review',
    priority: 'low',
    assigneeAgentId: 'demo-mobile-android',
    updatedAt: new Date(Date.now() - 900000).toISOString(),
    startedAt: new Date(Date.now() - 43200000).toISOString(),
  },
]

function dts(daysAgo: number, hour: number): string {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  d.setHours(hour, 0, 0, 0)
  return d.toISOString()
}

export const DEMO_ACTIVITY: ActivityEvent[] = [
  // ── Today ─────────────────────────────────────────────────────────────────
  { id: 'demo-evt-1', type: 'assigned', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-151', issueTitle: 'Mission Control Phase 3B — KPI sparklines', timestamp: dts(0, 9) },
  { id: 'demo-evt-2', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-149', issueTitle: 'Mission Control Phase 2 enhancements', timestamp: dts(0, 10) },
  { id: 'demo-evt-3', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-151', issueTitle: 'Phase 3B — KPI sparklines & heatmap', timestamp: dts(0, 11) },
  { id: 'demo-evt-4', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-152', issueTitle: 'Fix auth token refresh edge case', timestamp: dts(0, 14) },
  { id: 'demo-evt-5', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-148', issueTitle: 'Mission Control Phase 1 — CSS tokens', timestamp: dts(0, 9) },
  { id: 'demo-evt-6', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-153', issueTitle: 'Add lazy loading to agent card images', timestamp: dts(0, 13) },
  { id: 'demo-evt-7', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-144', issueTitle: 'Enhance and upgrade Dashboard', timestamp: dts(0, 10) },
  { id: 'demo-evt-8', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-147', issueTitle: 'Mission Control all-phases coordination', timestamp: dts(0, 15) },
  { id: 'demo-evt-9', type: 'done', agentId: 'demo-designer', agentName: 'Product Designer', agentRole: 'designer', issueIdentifier: 'APPU-145', issueTitle: 'Design UX/UI enhancement plan', timestamp: dts(0, 11) },
  { id: 'demo-evt-10', type: 'done', agentId: 'demo-ceo', agentName: 'CEO', agentRole: 'ceo', issueIdentifier: 'APPU-101', issueTitle: 'Q2 product strategy review', timestamp: dts(0, 14) },
  { id: 'demo-evt-11', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-138', issueTitle: 'Implement push notifications for mobile', timestamp: dts(0, 12) },
  { id: 'demo-evt-12', type: 'assigned', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-139', issueTitle: 'Deep link routing improvements', timestamp: dts(0, 13) },
  { id: 'demo-evt-13', type: 'blocked', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-132', issueTitle: 'Fix crash on settings screen open', timestamp: dts(0, 9) },

  // ── Yesterday ─────────────────────────────────────────────────────────────
  { id: 'h-y-1', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-143', issueTitle: 'Implement pipeline tabs UI', timestamp: dts(1, 10) },
  { id: 'h-y-2', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-142', issueTitle: 'Activity feed time dividers', timestamp: dts(1, 14) },
  { id: 'h-y-3', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-141', issueTitle: 'CSS variable system refactor', timestamp: dts(1, 9) },
  { id: 'h-y-4', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-136', issueTitle: 'Skeleton loading states', timestamp: dts(1, 11) },
  { id: 'h-y-5', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-135', issueTitle: 'Countdown ring animation', timestamp: dts(1, 15) },
  { id: 'h-y-6', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-146', issueTitle: 'Implement enhanced dashboard features', timestamp: dts(1, 10) },
  { id: 'h-y-7', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-134', issueTitle: 'Code review: Phase 1 PR', timestamp: dts(1, 14) },
  { id: 'h-y-8', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-133', issueTitle: 'Setup Vercel deployment pipeline', timestamp: dts(1, 16) },
  { id: 'h-y-9', type: 'done', agentId: 'demo-ceo', agentName: 'CEO', agentRole: 'ceo', issueIdentifier: 'APPU-130', issueTitle: 'Define Q2 goals and OKRs', timestamp: dts(1, 11) },
  { id: 'h-y-10', type: 'done', agentId: 'demo-ceo', agentName: 'CEO', agentRole: 'ceo', issueIdentifier: 'APPU-131', issueTitle: 'Stakeholder update memo', timestamp: dts(1, 15) },
  { id: 'h-y-11', type: 'done', agentId: 'demo-cto', agentName: 'CTO', agentRole: 'cto', issueIdentifier: 'APPU-140', issueTitle: 'Architecture review for Phase 2 components', timestamp: dts(1, 10) },
  { id: 'h-y-12', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-137', issueTitle: 'Haptic feedback on swipe gestures', timestamp: dts(1, 9) },
  { id: 'h-y-13', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-136', issueTitle: 'Offline mode graceful degradation', timestamp: dts(1, 13) },
  { id: 'h-y-14', type: 'done', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-128', issueTitle: 'Material You theming support', timestamp: dts(1, 10) },
  { id: 'h-y-15', type: 'done', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-127', issueTitle: 'Fix navigation backstack on Android', timestamp: dts(1, 14) },
  { id: 'h-y-16', type: 'error', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-132', issueTitle: 'Fix crash on settings screen open', timestamp: dts(1, 16) },
  { id: 'h-y-17', type: 'done', agentId: 'demo-designer', agentName: 'Product Designer', agentRole: 'designer', issueIdentifier: 'APPU-129', issueTitle: 'Dark mode icon set export', timestamp: dts(1, 11) },

  // ── 2 days ago ────────────────────────────────────────────────────────────
  { id: 'h-2-1', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-125', issueTitle: 'Glassmorphism card depth tier 2', timestamp: dts(2, 9) },
  { id: 'h-2-2', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-124', issueTitle: 'Agent card hover lift animation', timestamp: dts(2, 11) },
  { id: 'h-2-3', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-123', issueTitle: 'Status group capsule badges', timestamp: dts(2, 13) },
  { id: 'h-2-4', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-122', issueTitle: 'Blocked task amber shimmer', timestamp: dts(2, 15) },
  { id: 'h-2-5', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-121', issueTitle: 'Activity slide-in animation', timestamp: dts(2, 16) },
  { id: 'h-2-6', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-120', issueTitle: 'Priority badge color system', timestamp: dts(2, 9) },
  { id: 'h-2-7', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-119', issueTitle: 'Task row expand accordion', timestamp: dts(2, 12) },
  { id: 'h-2-8', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-118', issueTitle: 'Agent avatar initials coloring', timestamp: dts(2, 14) },
  { id: 'h-2-9', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-117', issueTitle: 'Relative timestamp tooltip', timestamp: dts(2, 16) },
  { id: 'h-2-10', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-116', issueTitle: 'Vite bundle split config', timestamp: dts(2, 10) },
  { id: 'h-2-11', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-115', issueTitle: 'Firebase emulator dev setup', timestamp: dts(2, 15) },
  { id: 'h-2-12', type: 'done', agentId: 'demo-ceo', agentName: 'CEO', agentRole: 'ceo', issueIdentifier: 'APPU-114', issueTitle: 'Investor update deck review', timestamp: dts(2, 11) },
  { id: 'h-2-13', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-113', issueTitle: 'Biometric auth integration', timestamp: dts(2, 10) },
  { id: 'h-2-14', type: 'done', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-112', issueTitle: 'ProGuard rules update', timestamp: dts(2, 13) },
  { id: 'h-2-15', type: 'done', agentId: 'demo-designer', agentName: 'Product Designer', agentRole: 'designer', issueIdentifier: 'APPU-111', issueTitle: 'Figma component library sync', timestamp: dts(2, 10) },

  // ── 3 days ago ────────────────────────────────────────────────────────────
  { id: 'h-3-1', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-110', issueTitle: 'Inter font integration', timestamp: dts(3, 9) },
  { id: 'h-3-2', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-109', issueTitle: 'Tabular nums CSS class', timestamp: dts(3, 12) },
  { id: 'h-3-3', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-108', issueTitle: 'Color token CSS variables', timestamp: dts(3, 15) },
  { id: 'h-3-4', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-107', issueTitle: 'Pulse ring keyframe animation', timestamp: dts(3, 10) },
  { id: 'h-3-5', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-106', issueTitle: 'Scanlines overlay effect', timestamp: dts(3, 14) },
  { id: 'h-3-6', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-105', issueTitle: 'React Query cache config', timestamp: dts(3, 9) },
  { id: 'h-3-7', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-104', issueTitle: 'TypeScript strict mode setup', timestamp: dts(3, 11) },
  { id: 'h-3-8', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-103', issueTitle: 'Tailwind config v3 upgrade', timestamp: dts(3, 14) },
  { id: 'h-3-9', type: 'done', agentId: 'demo-ceo', agentName: 'CEO', agentRole: 'ceo', issueIdentifier: 'APPU-102', issueTitle: 'Hiring plan Q2 approval', timestamp: dts(3, 10) },
  { id: 'h-3-10', type: 'done', agentId: 'demo-cto', agentName: 'CTO', agentRole: 'cto', issueIdentifier: 'APPU-100', issueTitle: 'System architecture review', timestamp: dts(3, 14) },
  { id: 'h-3-11', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-099', issueTitle: 'Swift async/await migration', timestamp: dts(3, 9) },
  { id: 'h-3-12', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-098', issueTitle: 'Widget extension MVP', timestamp: dts(3, 13) },
  { id: 'h-3-13', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-097', issueTitle: 'TestFlight build automation', timestamp: dts(3, 16) },
  { id: 'h-3-14', type: 'done', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-096', issueTitle: 'Jetpack Compose migration', timestamp: dts(3, 11) },
  { id: 'h-3-15', type: 'done', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-095', issueTitle: 'Room database schema v3', timestamp: dts(3, 15) },
  { id: 'h-3-16', type: 'done', agentId: 'demo-designer', agentName: 'Product Designer', agentRole: 'designer', issueIdentifier: 'APPU-094', issueTitle: 'Onboarding flow wireframes', timestamp: dts(3, 10) },
  { id: 'h-3-17', type: 'done', agentId: 'demo-designer', agentName: 'Product Designer', agentRole: 'designer', issueIdentifier: 'APPU-093', issueTitle: 'Error state illustration set', timestamp: dts(3, 14) },

  // ── 4 days ago ────────────────────────────────────────────────────────────
  { id: 'h-4-1', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-092', issueTitle: 'React 18 concurrent features setup', timestamp: dts(4, 10) },
  { id: 'h-4-2', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-091', issueTitle: 'Suspense boundary for agent grid', timestamp: dts(4, 13) },
  { id: 'h-4-3', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-090', issueTitle: 'Keyboard shortcut hint bar', timestamp: dts(4, 9) },
  { id: 'h-4-4', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-089', issueTitle: 'Filter dropdown accessibility', timestamp: dts(4, 12) },
  { id: 'h-4-5', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-088', issueTitle: 'Mobile responsive breakpoints', timestamp: dts(4, 16) },
  { id: 'h-4-6', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-087', issueTitle: 'CI pipeline GitHub Actions', timestamp: dts(4, 10) },
  { id: 'h-4-7', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-086', issueTitle: 'ESLint strict rules config', timestamp: dts(4, 15) },
  { id: 'h-4-8', type: 'done', agentId: 'demo-ceo', agentName: 'CEO', agentRole: 'ceo', issueIdentifier: 'APPU-085', issueTitle: 'Partner outreach strategy', timestamp: dts(4, 11) },
  { id: 'h-4-9', type: 'done', agentId: 'demo-ceo', agentName: 'CEO', agentRole: 'ceo', issueIdentifier: 'APPU-084', issueTitle: 'Brand positioning review', timestamp: dts(4, 14) },
  { id: 'h-4-10', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-083', issueTitle: 'iOS 17 API adoption plan', timestamp: dts(4, 10) },
  { id: 'h-4-11', type: 'done', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-082', issueTitle: 'Firebase crashlytics v2', timestamp: dts(4, 9) },
  { id: 'h-4-12', type: 'done', agentId: 'demo-designer', agentName: 'Product Designer', agentRole: 'designer', issueIdentifier: 'APPU-081', issueTitle: 'Design system audit', timestamp: dts(4, 13) },

  // ── 5 days ago ────────────────────────────────────────────────────────────
  { id: 'h-5-1', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-080', issueTitle: 'Zustand store composition patterns', timestamp: dts(5, 10) },
  { id: 'h-5-2', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-079', issueTitle: 'Vite alias config cleanup', timestamp: dts(5, 9) },
  { id: 'h-5-3', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-078', issueTitle: 'React Query devtools integration', timestamp: dts(5, 13) },
  { id: 'h-5-4', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-077', issueTitle: 'Monorepo workspace setup', timestamp: dts(5, 10) },
  { id: 'h-5-5', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-076', issueTitle: 'Turborepo pipeline optimization', timestamp: dts(5, 14) },
  { id: 'h-5-6', type: 'done', agentId: 'demo-cto', agentName: 'CTO', agentRole: 'cto', issueIdentifier: 'APPU-075', issueTitle: 'Security audit for Firebase rules', timestamp: dts(5, 11) },
  { id: 'h-5-7', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-074', issueTitle: 'Push notification categories', timestamp: dts(5, 9) },
  { id: 'h-5-8', type: 'done', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-073', issueTitle: 'WorkManager background sync', timestamp: dts(5, 10) },
  { id: 'h-5-9', type: 'done', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-072', issueTitle: 'App bundle APK split config', timestamp: dts(5, 15) },
  { id: 'h-5-10', type: 'done', agentId: 'demo-designer', agentName: 'Product Designer', agentRole: 'designer', issueIdentifier: 'APPU-071', issueTitle: 'Motion design system docs', timestamp: dts(5, 12) },

  // ── 6 days ago ────────────────────────────────────────────────────────────
  { id: 'h-6-1', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-070', issueTitle: 'Initial project scaffold', timestamp: dts(6, 9) },
  { id: 'h-6-2', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-069', issueTitle: 'Tailwind base config', timestamp: dts(6, 12) },
  { id: 'h-6-3', type: 'done', agentId: 'demo-web-2', agentName: 'Senior Web Engineer II', agentRole: 'engineer', issueIdentifier: 'APPU-068', issueTitle: 'Demo mode detection pattern', timestamp: dts(6, 15) },
  { id: 'h-6-4', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-067', issueTitle: 'Vite + React 18 project setup', timestamp: dts(6, 9) },
  { id: 'h-6-5', type: 'done', agentId: 'demo-web-1', agentName: 'Senior Web Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-066', issueTitle: 'Firebase SDK integration', timestamp: dts(6, 13) },
  { id: 'h-6-6', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-065', issueTitle: 'Task scoping and breakdown', timestamp: dts(6, 10) },
  { id: 'h-6-7', type: 'done', agentId: 'demo-lead-app', agentName: 'Lead App Engineer', agentRole: 'engineer', issueIdentifier: 'APPU-064', issueTitle: 'Vercel deployment config', timestamp: dts(6, 14) },
  { id: 'h-6-8', type: 'done', agentId: 'demo-ceo', agentName: 'CEO', agentRole: 'ceo', issueIdentifier: 'APPU-063', issueTitle: 'Project kickoff and goal setting', timestamp: dts(6, 9) },
  { id: 'h-6-9', type: 'done', agentId: 'demo-mobile-ios', agentName: 'Mobile Engineer iOS', agentRole: 'engineer', issueIdentifier: 'APPU-062', issueTitle: 'Xcode project dependency setup', timestamp: dts(6, 11) },
  { id: 'h-6-10', type: 'done', agentId: 'demo-mobile-android', agentName: 'Mobile Engineer Android', agentRole: 'engineer', issueIdentifier: 'APPU-061', issueTitle: 'Gradle version catalog setup', timestamp: dts(6, 10) },
  { id: 'h-6-11', type: 'done', agentId: 'demo-designer', agentName: 'Product Designer', agentRole: 'designer', issueIdentifier: 'APPU-060', issueTitle: 'Initial wireframe sketches', timestamp: dts(6, 9) },
]
