import type { Agent, Issue, ActivityEvent } from './types'

export const DEMO_AGENTS: Agent[] = [
  {
    id: 'demo-ceo',
    name: 'CEO',
    title: 'Chief Executive Officer',
    role: 'ceo',
    icon: 'crown',
    status: 'running',
    activeRun: {
      id: 'run-ceo-1',
      status: 'running',
      startedAt: new Date(Date.now() - 120000).toISOString(),
    },
    urlKey: 'ceo',
    currentIssue: { identifier: 'APPU-101', title: 'Q2 product strategy review' },
  },
  {
    id: 'demo-cto',
    name: 'CTO',
    title: 'Chief Technology Officer',
    role: 'cto',
    icon: 'chip',
    status: 'running',
    activeRun: null,
    urlKey: 'cto',
  },
  {
    id: 'demo-lead-app',
    name: 'Lead App Engineer',
    title: 'Lead Application Engineer',
    role: 'engineer',
    icon: 'rocket',
    status: 'running',
    activeRun: {
      id: 'run-lae-1',
      status: 'running',
      startedAt: new Date(Date.now() - 45000).toISOString(),
    },
    urlKey: 'lead-app-engineer',
    currentIssue: { identifier: 'APPU-149', title: 'Mission Control Phase 2 enhancements' },
  },
  {
    id: 'demo-designer',
    name: 'Product Designer',
    title: 'Product Designer',
    role: 'designer',
    icon: 'palette',
    status: 'running',
    activeRun: null,
    urlKey: 'product-designer',
  },
  {
    id: 'demo-web-1',
    name: 'Senior Web Engineer',
    title: 'Senior Web Engineer',
    role: 'engineer',
    icon: 'code',
    status: 'running',
    activeRun: {
      id: 'run-web1-1',
      status: 'running',
      startedAt: new Date(Date.now() - 200000).toISOString(),
    },
    urlKey: 'senior-web-engineer',
    currentIssue: { identifier: 'APPU-148', title: 'Mission Control Phase 1 — CSS tokens' },
  },
  {
    id: 'demo-web-2',
    name: 'Senior Web Engineer II',
    title: 'Senior Web Engineer II',
    role: 'engineer',
    icon: 'code',
    status: 'running',
    activeRun: {
      id: 'run-web2-1',
      status: 'running',
      startedAt: new Date(Date.now() - 5000).toISOString(),
    },
    urlKey: 'senior-web-engineer-ii',
    currentIssue: { identifier: 'APPU-149', title: 'Mission Control Phase 2 enhancements' },
  },
  {
    id: 'demo-mobile-ios',
    name: 'Mobile Engineer iOS',
    title: 'Senior Mobile Engineer iOS',
    role: 'engineer',
    icon: 'mobile',
    status: 'running',
    activeRun: null,
    urlKey: 'mobile-engineer-ios',
  },
  {
    id: 'demo-mobile-android',
    name: 'Mobile Engineer Android',
    title: 'Senior Mobile Engineer Android',
    role: 'engineer',
    icon: 'mobile',
    status: 'running',
    activeRun: null,
    urlKey: 'mobile-engineer-android',
  },
]

export const DEMO_PIPELINE_ISSUES: Issue[] = [
  {
    id: 'demo-ip-1',
    identifier: 'APPU-148',
    title: 'Mission Control Phase 1 — CSS tokens, typography, animations & badges',
    status: 'in_progress',
    priority: 'high',
    assigneeAgentId: 'demo-web-1',
    updatedAt: new Date(Date.now() - 200000).toISOString(),
    startedAt: new Date(Date.now() - 200000).toISOString(),
  },
  {
    id: 'demo-ip-2',
    identifier: 'APPU-149',
    title: 'Mission Control Phase 2 — Glassmorphism, pipeline tabs, activity feed',
    status: 'in_progress',
    priority: 'high',
    assigneeAgentId: 'demo-web-2',
    updatedAt: new Date(Date.now() - 5000).toISOString(),
    startedAt: new Date(Date.now() - 5000).toISOString(),
  },
  {
    id: 'demo-ip-3',
    identifier: 'APPU-101',
    title: 'Q2 product strategy review and roadmap planning',
    status: 'in_progress',
    priority: 'critical',
    assigneeAgentId: 'demo-ceo',
    updatedAt: new Date(Date.now() - 120000).toISOString(),
    startedAt: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'demo-ip-4',
    identifier: 'APPU-145',
    title: 'Design UX/UI enhancement plan for Mission Control dashboard',
    status: 'in_progress',
    priority: 'medium',
    assigneeAgentId: 'demo-designer',
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    startedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-blocked-1',
    identifier: 'APPU-150',
    title: 'Mission Control Phase 3A — Agent detail drawer & command palette',
    status: 'blocked',
    priority: 'medium',
    assigneeAgentId: 'demo-web-1',
    blockedBy: [
      { id: 'demo-ip-1', identifier: 'APPU-148', title: 'Phase 1 CSS tokens', status: 'in_progress' },
      { id: 'demo-ip-2', identifier: 'APPU-149', title: 'Phase 2 enhancements', status: 'in_progress' },
    ],
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'demo-blocked-2',
    identifier: 'APPU-151',
    title: 'Mission Control Phase 3B — KPI sparklines & activity heatmap',
    status: 'blocked',
    priority: 'low',
    assigneeAgentId: 'demo-web-2',
    blockedBy: [
      { id: 'demo-ip-2', identifier: 'APPU-149', title: 'Phase 2 enhancements', status: 'in_progress' },
    ],
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'demo-ir-1',
    identifier: 'APPU-138',
    title: 'Implement push notification system for mobile',
    status: 'in_review',
    priority: 'high',
    assigneeAgentId: 'demo-mobile-ios',
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    startedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'demo-ir-2',
    identifier: 'APPU-133',
    title: 'Add dark mode support to settings screen',
    status: 'in_review',
    priority: 'low',
    assigneeAgentId: 'demo-mobile-android',
    updatedAt: new Date(Date.now() - 900000).toISOString(),
    startedAt: new Date(Date.now() - 43200000).toISOString(),
  },
]

export const DEMO_ACTIVITY: ActivityEvent[] = [
  {
    id: 'demo-evt-1',
    type: 'assigned',
    agentId: 'demo-web-2',
    agentName: 'Senior Web Engineer II',
    agentRole: 'engineer',
    issueIdentifier: 'APPU-149',
    issueTitle: 'Mission Control Phase 2 enhancements',
    timestamp: new Date(Date.now() - 5000).toISOString(),
  },
  {
    id: 'demo-evt-2',
    type: 'assigned',
    agentId: 'demo-web-1',
    agentName: 'Senior Web Engineer',
    agentRole: 'engineer',
    issueIdentifier: 'APPU-148',
    issueTitle: 'Mission Control Phase 1 — CSS tokens',
    timestamp: new Date(Date.now() - 200000).toISOString(),
  },
  {
    id: 'demo-evt-3',
    type: 'blocked',
    agentId: 'demo-web-2',
    agentName: 'Senior Web Engineer II',
    agentRole: 'engineer',
    issueIdentifier: 'APPU-151',
    issueTitle: 'Phase 3B — KPI sparklines & heatmap',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'demo-evt-4',
    type: 'done',
    agentId: 'demo-designer',
    agentName: 'Product Designer',
    agentRole: 'designer',
    issueIdentifier: 'APPU-145',
    issueTitle: 'Design UX/UI enhancement plan',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-evt-5',
    type: 'assigned',
    agentId: 'demo-mobile-ios',
    agentName: 'Mobile Engineer iOS',
    agentRole: 'engineer',
    issueIdentifier: 'APPU-138',
    issueTitle: 'Implement push notifications for mobile',
    timestamp: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: 'demo-evt-6',
    type: 'done',
    agentId: 'demo-cto',
    agentName: 'CTO',
    agentRole: 'cto',
    issueIdentifier: 'APPU-140',
    issueTitle: 'Architecture review for Phase 2 components',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'demo-evt-7',
    type: 'error',
    agentId: 'demo-mobile-android',
    agentName: 'Mobile Engineer Android',
    agentRole: 'engineer',
    issueIdentifier: 'APPU-132',
    issueTitle: 'Fix crash on settings screen open',
    timestamp: new Date(Date.now() - 86400000 + 3600000).toISOString(),
  },
  {
    id: 'demo-evt-8',
    type: 'done',
    agentId: 'demo-lead-app',
    agentName: 'Lead App Engineer',
    agentRole: 'engineer',
    issueIdentifier: 'APPU-144',
    issueTitle: 'Enhance and upgrade Dashboard',
    timestamp: new Date(Date.now() - 86400000 + 1800000).toISOString(),
  },
  {
    id: 'demo-evt-9',
    type: 'blocked',
    agentId: 'demo-web-1',
    agentName: 'Senior Web Engineer',
    agentRole: 'engineer',
    issueIdentifier: 'APPU-150',
    issueTitle: 'Phase 3A — Agent detail drawer',
    timestamp: new Date(Date.now() - 86400000 + 900000).toISOString(),
  },
  {
    id: 'demo-evt-10',
    type: 'done',
    agentId: 'demo-ceo',
    agentName: 'CEO',
    agentRole: 'ceo',
    issueIdentifier: 'APPU-130',
    issueTitle: 'Define Q2 goals and OKRs',
    timestamp: new Date(Date.now() - 172800000 + 7200000).toISOString(),
  },
]
